apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "namespace-admission-controller.fullname" . }}
  labels:
    {{- include "namespace-admission-controller.labels" . | nindent 4 }}
data:
  CERTFILE_PATH: /etc/admission-controller/certs/cert.pem
  CLUSTER_ID: {{ .Values.rancher.clusterID }}
  KEYFILE_PATH: /etc/admission-controller/certs/key.pem
  RANCHER_API_TOKEN: {{ .Values.rancher.apiToken }}
  RANCHER_URL: {{ .Values.rancher.url }}
