{{ $tls := fromYaml ( include "admission-controller.gen-certs" . ) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "namespace-admission-controller.fullname" . }}
  labels:
    {{- include "namespace-admission-controller.labels" . | nindent 4 }}
data:
  cert.pem: {{ $tls.clientCert }}
  key.pem: {{ $tls.clientKey }}
