{{ $tls := fromYaml ( include "admission-controller.validating.gen-certs" . ) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "namespace-admission-controller.validating.fullname" . }}
  labels:
    {{- include "namespace-admission-controller.validating.labels" . | nindent 4 }}
data:
  cert.pem: {{ $tls.clientCert }}
  key.pem: {{ $tls.clientKey }}
