{{ $tls := fromYaml ( include "admission-controller.validating.gen-certs" . ) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "namespace-admission-controller.validating.fullname" . }}
  labels:
    {{- include "namespace-admission-controller.validating.labels" . | nindent 4 }}
data:
  cert.pem: {{ $tls.clientCert }}
  key.pem: {{ $tls.clientKey }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "namespace-admission-controller.validating.fullname" . }}
  labels:
    {{- include "namespace-admission-controller.validating.labels" . | nindent 4 }}
webhooks:
- name: {{ include "namespace-admission-controller.validating.service.fullname" . }}
  admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $tls.caCert }}
    service:
      name: {{ include "namespace-admission-controller.validating.service.name" . }}
      namespace: {{ .Release.Namespace }}
      path: "/"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["namespaces"]
  sideEffects: None
  timeoutSeconds: 5
