name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v1

      - name: Build
        run: |
          helm package namespace-admission-controller
          helm repo index .
          mkdir public
          mv namespace-admission-controller*.tgz ./public
          mv index.yaml ./public

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ github.token }}
